### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [36]:
import numpy as np

def is_prime(x: int):
    for i in range(2, x-1):
        if x % i == 0:
            return False

    return True


#1 CREAZIONE ARRAY
primi = np.array([i for i in range(2, 20) if is_prime(i)])

print('primi', primi)

#2 SELEZIONE DELLE VOCI >10
print('primi > 10:', primi[primi>10])

#3 SELEZIONE NUMERI PARI
print('pari:', primi[primi%2 == 0])

primi [ 2  3  5  7 11 13 17 19]
primi > 10: [11 13 17 19]
pari: [2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [37]:
a = np.arange(20).reshape((4,5))
print('a:', a)

b = a[[1,3]]
print('b:', b)

c = a[2,]
print('c', c)


a/c

a: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
b: [[ 5  6  7  8  9]
 [15 16 17 18 19]]
c [10 11 12 13 14]


array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.5       , 0.54545455, 0.58333333, 0.61538462, 0.64285714],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.5       , 1.45454545, 1.41666667, 1.38461538, 1.35714286]])

### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [38]:
a = np.random.rand(10,3)

b = np.abs(a-0.5)
print(b)

c = np.argmin(b, axis = 1)
print(c)

a[ np.arange(a.shape[0]), np.argmin(b, axis = 1)]

[[0.36609427 0.3866884  0.2553633 ]
 [0.20129725 0.18320478 0.42575712]
 [0.35427293 0.08444994 0.16535793]
 [0.25932749 0.08500008 0.43112957]
 [0.46763229 0.26129962 0.2504087 ]
 [0.40810627 0.23815325 0.13876329]
 [0.3695518  0.41970764 0.34179171]
 [0.24264161 0.2028205  0.44037755]
 [0.42505516 0.38242293 0.30227253]
 [0.3874685  0.13333792 0.27232628]]
[2 1 1 1 2 2 2 1 2 1]


array([0.7553633 , 0.31679522, 0.41555006, 0.41499992, 0.2495913 ,
       0.36123671, 0.84179171, 0.2971795 , 0.19772747, 0.36666208])

### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [39]:
#1 CREAZIONE ARRAY
array = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
print(array)

#2 TROVO FREQUENZA MINIMA
minimo = np.min(array)
print ('Minimo: ', minimo)

#3 TROVO FREQUENZA MASSIMA
massimo = np.max(array)
print('Massimo', massimo)

#4
new = array > 120
print(new)

#CALCOLO MEDIA E POI PERCENTUALE
perc = np.mean(new) * 100
print("Percentuale sopra 120:", perc)

[ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70]
Minimo:  60
Massimo 164
[False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]
Percentuale sopra 120: 52.38095238095239


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [40]:
#1 creazione array
stipendi = np.array([50000, 105250, 55000, 89000])

somma = np.sum(stipendi)
print('Somma segli stipendi: ', somma)

#2 aumento CEO
stipendi[1]= stipendi[1] + stipendi[1] * 0.15
print(stipendi)


Somma segli stipendi:  299250
[ 50000 121037  55000  89000]


**DOMANDA 3**


l'array è formato da soli interi; quindi lo converte forzatamente a intero troncando la parte decimale

In [41]:
#4 ricreo array float
stipendi = np.array([50000, 105250, 55000, 89000], dtype=float)
stipendi[1] *= 1.15

print(stipendi) 

#5 aumento di stipendio
stipendi[0] *= 1.20
print(stipendi)

#6 aumento degli altri
stipendi[[2, 3]] *= 1.10
print(stipendi)

#costo totale
print('costo totale: ', np.sum(stipendi))

[ 50000.  121037.5  55000.   89000. ]
[ 60000.  121037.5  55000.   89000. ]
[ 60000.  121037.5  60500.   97900. ]
costo totale:  339437.5


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [42]:
co2 = np.loadtxt('../DATI/emissioni.txt')
print(co2)

#conta valori > 18 tonnellate e media
selezione = co2[co2>18]
print(selezione)

count = selezione.size
print('valori sopra la soglia: ', count)

media = np.mean(selezione)
print('valore medio: ', media)

#frazione totale
frazione = np.sum(selezione)/np.sum(co2)
print('frazione: ', frazione)

[ 8.58  5.08  5.48  9.65 13.76 14.35  8.92 13.34  6.58  5.32  4.87  9.67
 11.96 17.41  9.35 19.39 12.78  8.46  9.37  7.53 11.01 14.02 14.6   7.25
 16.18 19.88 17.23 15.14 19.31 12.49 10.34 18.2   4.87 11.75  8.01 13.52
 15.   10.71  9.45 16.01  7.5  19.3   6.61 12.27 18.24  7.31 19.11  5.81
 16.73  9.87  5.73  4.93  5.19  7.34 18.14 16.79 17.82 11.73 17.8   9.81
 14.91  7.2   9.18 15.53 12.56  6.18 13.87  5.82  7.94  6.57 19.33 15.02
 18.23 14.01  8.96  7.71  9.65 12.06  4.56 12.84 18.44 13.87 17.76  5.09
 15.4  11.59  9.7   5.85 11.21 19.69 19.67 18.58 19.33  8.79 18.25 11.65
 10.99 10.05 11.63 16.05 12.96 13.34  4.42 11.67 17.78  9.86 11.4   8.5
  8.47  9.67  4.91  7.94 10.94  9.03 12.72  9.01 18.8   5.9   5.91  6.26
  8.23 15.42  7.26 18.71 11.66 16.16 18.39  4.78 17.45 19.62 18.96 16.77
 19.44  6.99 14.48  7.34 10.24  4.77 16.88 11.61  6.28  7.77 14.82 15.35
 11.57  6.48 16.91 18.02 18.44  4.85  8.22  9.17 15.55 13.94 10.81  7.23
 10.61 14.42 14.9  14.52  9.62 11.94 13.17 14.21  5.

### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [43]:
survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13] ])

#1 PRENDO LA TERZA COLONNA E FILTRO
NEW = survey_matrix[survey_matrix[:,2]>= 12]
print(NEW)

#2 SELEZIONE REDDITI CON ISTRUZIONE>=12
selezione = NEW[:,1]
print(selezione)

#3 REDDUTO MEDIO
media = np.mean(selezione)
print('media: ', media)

[[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
[52000 63000 58000]
media:  57666.666666666664


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [44]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

nuovo = ages[ages!=999]

massimo = nuovo.max()
print('valore massimo: ', massimo)

valore massimo:  112


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [45]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]



In [46]:
parole_array = np.array(lista_parole)
print(parole_array)

#scelgo 5 valori casuali
indici = np.random.randint(0, len(parole_array), 5)

parole = parole_array[indici]

storia = f'''In epoche passate, viveva una donna saggia che era molto orgogliosa dell 'antico {parole[0]} che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il {parole[1]} come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "{parole[2]}".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {parole[3]}.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all 'altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {parole[4]}!" Ci fu grande gioia e celebrazione.'''


print(storia)

['INSEDIAMENTO' 'SEPARAZIONE' 'DIFFERENZA' 'APPLICAZIONE' 'ATTEGGIAMENTO'
 'VERDURA' 'IMPERO' 'RICEVIMENTO' 'IGNORANZA' 'BIOGRAFIA' 'VISIONE'
 'AGENTE DI POLIZIA' 'PROVA' 'PRESTAZIONE' 'PRESENTAZIONE' 'PARENTE'
 'GIUSTIFICAZIONE' 'FILOSOFIA' 'DIREZIONE' 'BENEFICIARIO' 'BATTERIA'
 'CERIMONIA' 'AGONIA' 'RECUPERO' 'ALFABETIZZAZIONE' 'CONSEGNA' 'SERBATOIO'
 'VOLONTARIO' 'DEPOSITO' 'BIRILLO DA BOWLING' 'NEMICO' 'ANNUNCIO'
 'CARAMELLA ZUCCHERATA' 'FULMINE' 'PALLONCINO' 'COPERTA' 'SCOPERTA'
 'PENALITÀ' 'GENERALE' 'ALPACA' 'VANTAGGIO' 'HOT DOG' 'ABITO' 'MATEMATICA'
 'VARIANTE']
In epoche passate, viveva una donna saggia che era molto orgogliosa dell 'antico VERDURA che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il APPLICAZIONE come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "BENEFICIARIO".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono 

Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."

MIO ESEMPIO DI OUTPUT:


In epoche passate, viveva una donna saggia che era molto orgogliosa dell 'antico VERDURA che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il APPLICAZIONE come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "BENEFICIARIO".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un GENERALE.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all 'altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza MATEMATICA!" Ci fu grande gioia e celebrazione.